apiVersion: v1
data:
  SERVICE_VERSION: latest
  spring.profiles.active: local
kind: ConfigMap
metadata:
  name: order-service
  namespace: kind-local
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: order-service
    service: order-service
  name: order-service
  namespace: kind-local
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: order-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: order-service
    version: latest
  name: order-service
  namespace: kind-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
        version: latest
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: order-service
            optional: true
        - configMapRef:
            name: order-service-terraform
            optional: true
        - secretRef:
            name: order-service
            optional: true
        - secretRef:
            name: order-service-terraform
            optional: true
        image: order-service:latest
        imagePullPolicy: Never
        name: order-service
        ports:
        - containerPort: 8080
