apiVersion: v1
data:
  SERVICE_VERSION: latest
  spring.profiles.active: local
kind: ConfigMap
metadata:
  name: web-app
  namespace: kind-local
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-app
    service: web-app
  name: web-app
  namespace: kind-local
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: web-app
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-app
    version: latest
  name: web-app
  namespace: kind-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
        version: latest
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: web-app
            optional: true
        - configMapRef:
            name: web-app-terraform
            optional: true
        - secretRef:
            name: web-app
            optional: true
        - secretRef:
            name: web-app-terraform
            optional: true
        image: web-app:latest
        imagePullPolicy: Never
        name: web-app
        ports:
        - containerPort: 8080
